apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
provisioner: example.local/nfs
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  archiveOnDelete: "false"
